[project]
name = "simple-pub-sub"
version = "0.1.0"
description = "Add a short description here"
authors = ["Girish Joshi <mail@girishjoshi.io>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
start = "cargo run"
build = "cargo build"
test = "cargo test"
clean = "cargo clean"
fmt = "cargo fmt"
lint = { cmd = "cargo clippy", depends_on = ["fmt"] }

[dependencies]
