[package]
name = "simple-pub-sub-message"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
anyhow = "1.0.97"
tokio = { version = "1", features = ["full", "tracing"] }
log = "0.4.26"

[dev-dependencies]
uuid = { version = "1.6.1", features = ["v4"] }
env_logger = "0.11.3"
