name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master, dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose --workspace
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: simple-pub-sub # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            target/release/simple-pub-sub
            target/release/simple-pub-sub.bash
            target/release/simple-pub-sub.1
